In [1]:
#importing packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#read dataset
dataset = pd.read_csv(r"D:\dataset AIML\diabetes.csv")

In [5]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [8]:
dataset.shape

(768, 9)

In [9]:
#data cleaning
dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
dataset.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [12]:
dataset.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [14]:
for i in dataset.columns:
    print(i,':','\n',dataset[i].unique(),'\n')

Pregnancies : 
 [ 6  1  8  0  5  3 10  2  4  7  9 11 13 15 17 12 14] 

Glucose : 
 [148  85 183  89 137 116  78 115 197 125 110 168 139 189 166 100 118 107
 103 126  99 196 119 143 147  97 145 117 109 158  88  92 122 138 102  90
 111 180 133 106 171 159 146  71 105 101 176 150  73 187  84  44 141 114
  95 129  79   0  62 131 112 113  74  83 136  80 123  81 134 142 144  93
 163 151  96 155  76 160 124 162 132 120 173 170 128 108 154  57 156 153
 188 152 104  87  75 179 130 194 181 135 184 140 177 164  91 165  86 193
 191 161 167  77 182 157 178  61  98 127  82  72 172  94 175 195  68 186
 198 121  67 174 199  56 169 149  65 190] 

BloodPressure : 
 [ 72  66  64  40  74  50   0  70  96  92  80  60  84  30  88  90  94  76
  82  75  58  78  68 110  56  62  85  86  48  44  65 108  55 122  54  52
  98 104  95  46 102 100  61  24  38 106 114] 

SkinThickness : 
 [35 29  0 23 32 45 19 47 38 30 41 33 26 15 36 11 31 37 42 25 18 24 39 27
 21 34 10 60 13 20 22 28 54 40 51 56 14 17 50 44 12 46 16  

In [18]:
dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [26]:
dataset['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [28]:
#inputand output separation
ip = dataset.drop('Outcome' , axis = 1)
op = dataset['Outcome']

In [29]:
ip

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [30]:
op


0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [75]:
#train_test_split
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(ip , op , test_size=0.2 , random_state = 4)

In [76]:
x_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
596            0       67             76              0        0  45.3   
90             1       80             55              0        0  19.1   
734            2      105             75              0        0  23.3   
694            2       90             60              0        0  23.5   
517            7      125             86              0        0  37.6   
..           ...      ...            ...            ...      ...   ...   
360            5      189             64             33      325  31.2   
709            2       93             64             32      160  38.0   
439            6      107             88              0        0  36.8   
174            2       75             64             24       55  29.7   
122            2      107             74             30      100  33.6   

     DiabetesPedigreeFunction  Age  
596                     0.194   46  
90                      0.258   21  
734                     0.560   53  
694                     0.191   25  
517                     0.304   51  
..                        ...  ...  
360                     0.583   29  
709                     0.674   23  
439                     0.727   31  
174                     0.370   33  
122                     0.404   23  

[614 rows x 8 columns]

In [77]:
x_test

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
390            1      100             66             29      196  32.0   
146            9       57             80             37        0  32.8   
136            0      100             70             26       50  30.8   
420            1      119             88             41      170  45.3   
328            2      102             86             36      120  45.5   
..           ...      ...            ...            ...      ...   ...   
374            2      122             52             43      158  36.2   
288            4       96             56             17       49  20.8   
282            7      133             88             15      155  32.4   
754            8      154             78             32        0  32.4   
363            4      146             78              0        0  38.5   

     DiabetesPedigreeFunction  Age  
390                     0.444   42  
146                     0.096   41  
136                     0.597   21  
420                     0.507   26  
328                     0.127   23  
..                        ...  ...  
374                     0.816   28  
288                     0.340   26  
282                     0.262   37  
754                     0.443   45  
363                     0.520   67  

[154 rows x 8 columns]

In [78]:
y_train

596    0
90     0
734    0
694    0
517    0
      ..
360    1
709    1
439    0
174    0
122    0
Name: Outcome, Length: 614, dtype: int64

In [79]:
y_test

390    0
146    0
136    0
420    0
328    1
      ..
374    0
288    0
282    0
754    1
363    1
Name: Outcome, Length: 154, dtype: int64

In [80]:
#standardization of data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [81]:
x_train

array([[-1.13297401, -1.70544954,  0.3837674 , ...,  1.63727815,
        -0.83696713,  1.09138367],
       [-0.83670227, -1.29149491, -0.6919493 , ..., -1.55372817,
        -0.6446041 , -1.0400081 ],
       [-0.54043053, -0.4954283 ,  0.33254279, ..., -1.04219281,
         0.26310891,  1.68817336],
       ...,
       [ 0.64465642, -0.43174297,  0.99846265, ...,  0.60202801,
         0.76505617, -0.18745139],
       [-0.54043053, -1.45070823, -0.23092786, ..., -0.26271035,
        -0.30796881, -0.01694005],
       [-0.54043053, -0.43174297,  0.28131819, ...,  0.21228678,
        -0.20577596, -0.86949676]])

In [82]:
x_test

array([[-0.87828835, -0.65366708, -0.29784688, ..., -0.08382837,
        -0.07865897,  0.72540472],
       [ 1.52093837, -1.91785615,  0.46210327, ...,  0.04196524,
        -1.1504849 ,  0.64096607],
       [-1.17819169, -0.65366708, -0.08071827, ..., -0.27251878,
         0.39257485, -1.04780682],
       ...,
       [ 0.92113169,  0.31652454,  0.89636049, ..., -0.02093157,
        -0.63921161,  0.3032115 ],
       [ 1.22103503,  0.9339192 ,  0.35353896, ..., -0.02093157,
        -0.08173893,  0.97872065],
       [ 0.02142167,  0.69872123,  0.35353896, ...,  0.9382447 ,
         0.15541796,  2.83637083]])

In [83]:
print(ip.shape ,x_train.shape , x_test.shape )


(768, 8) (614, 8) (154, 8)


In [84]:
#machine learning model
from sklearn.svm import SVC
svc = SVC(kernel = 'rbf' ,C = 1000 , gamma = 0.01)
svc.fit(x_train , y_train)

SVC(C=1000, gamma=0.01)

In [85]:
y_pred = svc.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0],
      dtype=int64)

In [86]:
#accuracy
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score
acc = accuracy_score(y_pred , y_test)
rec = recall_score(y_pred , y_test)
pre = precision_score(y_pred ,y_test)
f1 = f1_score(y_pred , y_test)

print('Accuracy:',acc)
print('recall:',rec)
print('precision:',pre)
print('f1 score:',f1)

Accuracy: 0.7662337662337663
recall: 0.6666666666666666
precision: 0.6153846153846154
f1 score: 0.64


In [89]:
#making a predictive system

input_data = (6,148,72,35,0,33.6,0.627,50)
input_data_as_numpy = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy.reshape(1,-1)
standard_data = sc.transform(input_data_reshaped)
prediction = svc.predict(standard_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

[1]
The person is diabetic


D:\anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
